### ISSUE TITLE
Requirement for compilation

### ISSUE THREAD

**Issue by farvardin** [jpcima/dessiner-un-son#1]
after some time struggling to find the right missing packages, here is a list (could be included in the readme):

libqwt-qt5-dev qt5-qmake qtbase5-dev-tools qtbase5-dev libqt5opengl5-dev libqt5multimediaquick-p5 qtmultimedia5-dev libspeexdsp-dev libboost1.62-dev

**Comment by jpcima** [comment]
Hi @farvardin. thanks for information, I'll include it.

I'm pretty sure though, this one is a mistake: `libqwt-qt5-dev`.
Nothing in this program was develop with qwt libraries.
Also `quick` versions of components weren't used, just c++-based ones.

I'll change `libboost1.62-dev` to `libboost-dev` (better to be version agnostic)
Second, I'll indicate `libqt5multimedia5-plugins`, because Qt is not able to output sound without it.

**Comment by jpcima** [comment]
Done, I've mentioned a set of required packages. (which I corrected here and there, but not verified)

**Comment by erwan35** [comment]
> I'm pretty sure though, this one is a mistake: libqwt-qt5-dev.

My mistake :)

**Comment by jpcima** [comment]
I think it's safe to close this one.
